# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lollipopkit.serverbox
PackageVersion: 1.0.1617
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ServerBox.exe
  PortableCommandAlias: serverbox
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-12
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lollipopkit/flutter_server_box/releases/download/v1.0.1617/ServerBox_v1.0.1617_windows_amd64.zip
  InstallerSha256: AEAA4835153062CB8FFA70CA59704CFA40436CDBC35D9351CBF2077BC4D1A632
ManifestType: installer
ManifestVersion: 1.12.0
